language: d
d:
  - ldc
matrix:
  # ARM64 testing is under development
  allow_failures:
    - os: osx
  include:
    - os: linux
      compiler: gcc
    - os: linux
      arch:
        - arm64
      compiler: gcc
    - os: osx
      compiler: clang
script:
  - make
  - make check
